//MODAL ACTIONS
export const OPEN_MODAL = 'OPEN_MODAL'

export const CLOSE_MODAL = 'CLOSE_MODAL'

//BOOK ACTIONS
export const FETCH_LIST_BOOK = 'FETCH_LIST_BOOK'

export const FETCH_LIST_BOOK_SUCCESS = 'FETCH_LIST_BOOK_SUCCESS'

export const FETCH_LIST_BOOK_FAILED = 'FETCH_LIST_BOOK_FAILED'

export const FETCH_ALL_PRODUCTS = 'FETCH_ALL_PRODUCTS'

export const GET_DETAIL_BOOK = 'GET_DETAIL_BOOK'

export const GET_DETAIL_BOOK_SUCCESS = 'GET_DETAIL_BOOK_SUCCESS'

export const GET_DETAIL_BOOK_FAILED = 'GET_DETAIL_BOOK_FAILED'

export const UPDATE_BOOK = 'UPDATE_BOOK'

export const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS'

export const UPDATE_BOOK_FAILED = 'UPDATE_BOOK_FAILED'

export const GET_LIST_BY_BF_ID = 'GET_LIST_BY_BF_ID'

export const GET_LIST_BY_BF_ID_SUCCESS = 'GET_LIST_BY_BF_ID_SUCCESS'

export const GET_LIST_BY_BF_ID_FAILED = 'GET_LIST_BY_BF_ID_FAILED'

export const GET_LIST_BEST_SELLER = 'GET_LIST_BEST_SELLER'

export const GET_LIST_BEST_SELLER_SUCCESS = 'GET_LIST_BEST_SELLER_SUCCESS'

export const GET_LIST_BEST_SELLER_FAILED = 'GET_LIST_BEST_SELLER_FAILED'

export const GET_LIST_BEST_SALES = 'GET_LIST_BEST_SALES'

export const GET_LIST_BEST_SALES_SUCCESS = 'GET_LIST_BEST_SALES_SUCCESS'

export const GET_LIST_BEST_SALES_FAILED = 'GET_LIST_BEST_SALES_FAILED'

export const GET_LIST_BEST_RATE = 'GET_LIST_BEST_RATE'

export const GET_LIST_BEST_RATE_SUCCESS = 'GET_LIST_BEST_RATE_SUCCESS'

export const GET_LIST_BEST_RATE_FAILED = 'GET_LIST_BEST_RATE_FAILED'

export const GET_LIST_NEWEST = 'GET_LIST_NEWEST'

export const GET_LIST_NEWEST_SUCCESS = 'GET_LIST_NEWEST_SUCCESS'

export const GET_LIST_NEWEST_FAILED = 'GET_LIST_NEWEST_FAILED'

export const FILTER_BOOKS = 'FILTER_BOOKS'

export const FILTER_BOOKS_SUCCESS = 'FILTER_BOOKS_SUCCESS'

export const FILTER_BOOKS_FAILED = 'FILTER_BOOKS_FAILED'

export const ADD_NEW_BOOK = 'ADD_NEW_BOOK'

export const ADD_NEW_BOOK_SUCCESS = 'ADD_NEW_BOOK_SUCCESS'

export const ADD_NEW_BOOK_FAILED = 'ADD_NEW_BOOK_FAILED'

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE'

export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS'

export const UPLOAD_IMAGE_FAILED = 'UPLOAD_IMAGE_FAILED'

export const GET_KEYWORD = 'GET_KEYWORD'

//FIELDSBOOK ACTIONS
export const FETCH_LIST_FIELDSBOOK = 'FETCH_LIST_FIELDSBOOK'

export const FETCH_LIST_FIELDSBOOK_SUCCESS = 'FETCH_LIST_FIELDSBOOK_SUCCESS'

export const FETCH_LIST_FIELDSBOOK_FAILED = 'FETCH_LIST_FIELDSBOOK_FAILED'

//CART ACTIONS
export const FETCH_CART = 'FETCH_CART'

export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS'

export const FETCH_CART_FAILED = 'FETCH_CART_FAILED'

export const ADD_TO_CART = 'ADD_TO_CART'

export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'

export const ADD_TO_CART_FAILED = 'ADD_TO_CART_FAILED'

export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART'

export const REMOVE_ITEM_FROM_CART_SUCCESS = 'REMOVE_ITEM_FROM_CART_SUCCESS'

export const REMOVE_ITEM_FROM_CART_FAILED = 'REMOVE_ITEM_FROM_CART_FAILED'

export const UPDATE_CART = 'UPDATE_CART'

export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS'

export const UPDATE_CART_FAILED = 'UPDATE_CART_FAILED'

//SPINNER ACTIONS
export const SHOW_LOADING = 'SHOW_LOADING'

export const HIDE_LOADING = 'HIDE_LOADING'

//ADDRESS ACTIONS
export const GET_LIST_ADDRESS = 'GET_LIST_ADDRESS'

export const GET_LIST_ADDRESS_SUCCESS = 'GET_LIST_ADDRESS_SUCCESS'

export const GET_LIST_ADDRESS_FAILED = 'GET_LIST_ADDRESS_FAILED'

export const CREATE_NEW_ADDRESS = 'CREATE_NEW_ADDRESS'

export const CREATE_NEW_ADDRESS_SUCCESS = 'CREATE_NEW_ADDRESS_SUCCESS'

export const CREATE_NEW_ADDRESS_FAILED = 'CREATE_NEW_ADDRESS_FAILED'

export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'

export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS'

export const UPDATE_ADDRESS_FAILED = 'UPDATE_ADDRESS_FAILED'

export const DELETE_ADDRESS = 'DELETE_ADDRESS'

export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS'

export const DELETE_ADDRESS_FAILED = 'DELETE_ADDRESS_FAILED'

//ORDER ACTIONS

export const FETCH_ALL_LIST_ORDER = 'FETCH_ALL_LIST_ORDER'

export const FETCH_ALL_LIST_ORDER_SUCCESS = 'FETCH_ALL_LIST_ORDER_SUCCESS'

export const FETCH_ALL_LIST_ORDER_FAILED = 'FETCH_ALL_LIST_ORDER_FAILED'

export const FETCH_DETAIL_ORDER = 'FETCH_DETAIL_ORDER'

export const FETCH_DETAIL_ORDER_SUCCESS = 'FETCH_DETAIL_ORDER_SUCCESS'

export const FETCH_DETAIL_ORDER_FAILED = 'FETCH_DETAIL_ORDER_FAILED'

export const FILTER_ORDER = 'FILTER_ORDER'

export const FILTER_ORDER_SUCCESS = 'FILTER_ORDER_SUCCESS'

export const FILTER_ORDER_FAILED = 'FILTER_ORDER_FAILED'

export const UPDATE_ORDER = 'UPDATE_ORDER'

export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS'

export const UPDATE_ORDER_FAILED = 'UPDATE_ORDER_FAILED'

export const CREATE_ORDER = 'CREATE_ORDER'

export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'

export const CREATE_ORDER_FAILED = 'CREATE_ORDER_FAILED'

export const DELETE_ORDER = 'DELETE_ORDER'

//COMMENT ACTIONS
export const GET_LIST_COMMENTS = 'GET_LIST_COMMENTS'

export const GET_LIST_COMMENTS_SUCCESS = 'GET_LIST_COMMENTS_SUCCESS'

export const GET_LIST_COMMENTS_FAILED = 'GET_LIST_COMMENTS_FAILED'

export const ADD_COMMENT = 'ADD_COMMENT'

export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'

export const ADD_COMMENT_FAILED = 'ADD_COMMENT_FAILED'

export const UPDATE_COMMENT = 'UPDATE_COMMENT'

export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS'

export const UPDATE_COMMENT_FAILED = 'UPDATE_COMMENT_FAILED'

export const DELETE_COMMENT = 'DELETE_COMMENT'

export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'

export const DELETE_COMMENT_FAILED = 'DELETE_COMMENT_FAILED'

//AUTHENTICAL ACTIONS
export const SIGN_UP = 'SIGN_UP'

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'

export const SIGN_UP_FAILED = 'SIGN_UP_FAILED'

export const SIGN_UP_MANAGER = 'SIGN_UP_MANAGER'

export const SIGN_UP_MANAGER_SUCCESS = 'SIGN_UP_MANAGER_SUCCESS'

export const SIGN_UP_MANAGER_FAILED = 'SIGN_UP_MANAGER_FAILED'

export const LOGIN = 'LOGIN'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const LOGIN_FAILED = 'LOGIN_FAILED'

export const LOGOUT = 'LOGOUT'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const LOGOUT_FAILED = 'LOGOUT_FAILED'

//ACCOUNT ACTIONS

export const GET_USER = 'GET_USER'

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'

export const GET_USER_FAILED = 'GET_USER_FAILED'

export const UPDATE_USER = 'UPDATE_USER'

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'

export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED'

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'

export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'

export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED'

export const DELETE_INFO = 'DELETE_INFO'

//RATE ACTIONS 

export const GET_LIST_RATE = 'GET_LIST_RATE'

export const GET_LIST_RATE_SUCCESS = 'GET_LIST_RATE_SUCCESS'

export const GET_LIST_RATE_FAILED = 'GET_LIST_RATE_FAILED'

export const RATE_BOOK = 'RATE_BOOK'

export const RATE_BOOK_SUCCESS = 'RATE_BOOK_SUCCESS'

export const RATE_BOOK_FAILED = 'RATE_BOOK_FAILED'

export const UPDATE_RATE = 'UPDATE_RATE'

export const UPDATE_RATE_SUCCESS = 'UPDATE_RATE_SUCCESS'

export const UPDATE_RATE_FAILED = 'UPDATE_RATE_FAILED'

export const FOUR_NEWEST = 'FOUR_NEWEST'

export const FOUR_NEWEST_SUCCESS = 'FOUR_NEWEST_SUCCESS'

export const FOUR_NEWEST_FAILED = 'FOUR_NEWEST_FAILED'

export const FOUR_BEST_SELLER = 'FOUR_BEST_SELLER'

export const FOUR_BEST_SELLER_SUCCESS = 'FOUR_BEST_SELLER_SUCCESS'

export const FOUR_BEST_SELLER_FAILED = 'FOUR_BEST_SELLERE_FAILED'

export const FOUR_BEST_DISCOUNT = 'FOUR_BEST_DISCOUNT'

export const FOUR_BEST_DISCOUNT_SUCCESS = 'FOUR_BEST_DISCOUNT_SUCCESS'

export const FOUR_BEST_DISCOUNT_FAILED = 'FOUR_BEST_DISCOUNT_FAILED'