//MODAL ACTIONS
export const OPEN_MODAL = 'OPEN_MODAL'

export const CLOSE_MODAL = 'CLOSE_MODAL'

//BOOK ACTIONS
export const FETCH_LIST_BOOK = 'FETCH_LIST_BOOK'

export const FETCH_LIST_BOOK_SUCCESS = 'FETCH_LIST_BOOK_SUCCESS'

export const FETCH_LIST_BOOK_FAILED = 'FETCH_LIST_BOOK_FAILED'

export const FETCH_ALL_PRODUCTS = 'FETCH_ALL_PRODUCTS'

export const GET_DETAIL_BOOK = 'GET_DETAIL_BOOK'

export const GET_DETAIL_BOOK_SUCCESS = 'GET_DETAIL_BOOK_SUCCESS'

export const GET_DETAIL_BOOK_FAILED = 'GET_DETAIL_BOOK_FAILED'


//FIELDSBOOK ACTIONS
export const FETCH_LIST_FIELDSBOOK = 'FETCH_LIST_FIELDSBOOK'

export const FETCH_LIST_FIELDSBOOK_SUCCESS = 'FETCH_LIST_FIELDSBOOK_SUCCESS'

export const FETCH_LIST_FIELDSBOOK_FAILED = 'FETCH_LIST_FIELDSBOOK_FAILED'

//CART ACTIONS
export const FETCH_CART = 'FETCH_CART'

export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS'

export const FETCH_CART_FAILED = 'FETCH_CART_FAILED'

export const ADD_TO_CART = 'ADD_TO_CART'

export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'

export const ADD_TO_CART_FAILED = 'ADD_TO_CART_FAILED'

export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART'

export const REMOVE_ITEM_FROM_CART_SUCCESS = 'REMOVE_ITEM_FROM_CART_SUCCESS'

export const REMOVE_ITEM_FROM_CART_FAILED = 'REMOVE_ITEM_FROM_CART_FAILED'

export const UPDATE_CART = 'UPDATE_CART'

export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS'

export const UPDATE_CART_FAILED = 'UPDATE_CART_FAILED'

//MESSAGE ACTIONS
export const CHANGE_MESSAGE  = 'CHANGE_MESSAGE ' 

//SPINNER ACTIONS
export const SHOW_LOADING = 'SHOW_LOADING'

export const HIDE_LOADING = 'HIDE_LOADING'

//FILTER BOOK ACTIONS
export const FILTER_BOOKS_SINGLE = 'FILTER_BOOKS_SINGLE'

export const FITLER_BOOKS_SINGLE_SUCCESS = 'FITLER_BOOKS_SINGLE_SUCCESS'

export const FITLER_BOOKS_SINGLE_FAILED = 'FITLER_BOOKS_SINGLE_FAILED'

export const FILTER_BOOKS_MULTI = 'FILTER_BOOKS_MULTI'

export const FITLER_BOOKS_MULTI_SUCCESS = 'FITLER_BOOKS_MULTI_SUCCESS'

export const FITLER_BOOKS_MULTI_FAILED = 'FITLER_BOOKS_MULTI_FAILED'

export const GET_KEYWORD = 'GET_KEYWORD'

//ADDRESS ACTIONS
export const GET_LIST_ADDRESS = 'GET_LIST_ADDRESS'

export const GET_LIST_ADDRESS_SUCCESS = 'GET_LIST_ADDRESS_SUCCESS'

export const GET_LIST_ADDRESS_FAILED = 'GET_LIST_ADDRESS_FAILED'

export const CREATE_NEW_ADDRESS = 'CREATE_NEW_ADDRESS'

export const CREATE_NEW_ADDRESS_SUCCESS = 'CREATE_NEW_ADDRESS_SUCCESS'

export const CREATE_NEW_ADDRESS_FAILED = 'CREATE_NEW_ADDRESS_FAILED'

export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'

export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS'

export const UPDATE_ADDRESS_FAILED = 'UPDATE_ADDRESS_FAILED'

export const DELETE_ADDRESS = 'DELETE_ADDRESS'

export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS'

export const DELETE_ADDRESS_FAILED = 'DELETE_ADDRESS_FAILED'

//INVOICE ACTIONS

export const FETCH_LIST_INVOICE = 'FETCH_LIST_INVOICE'

export const FETCH_LIST_INVOICE_SUCCESS = 'FETCH_LIST_INVOICE_SUCCESS'

export const FETCH_LIST_INVOICE_FAILED = 'FETCH_LIST_INVOICE_FAILED'

export const CREATE_INVOICE = 'CREATE_INVOICE'

export const CREATE_INVOICE_SUCCESS = 'CREATE_INVOICE_SUCCESS'

export const CREATE_INVOICE_FAILED = 'CREATE_INVOICE_FAILED'